name: Workflow A

on:
  push:
    branches:
      - release

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print some variables
        run: |
          echo ${{ github.event.workflow_run.head_branch }}
          echo ${{ github.event.workflow_run.head_sha }}
