name: Workflow B

on:
  workflow_run:
    workflows: ['Workflow A']
    types: [completed]

jobs:
  print-current-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Print git log
        run: git log --oneline

      - name: Print some variables
        run: |
          echo ${{ github.event.workflow_run.head_branch }}
          echo ${{ github.event.workflow_run.head_sha }}
