name: Workflow B

on:
  workflow_run:
    workflows: ['Workflow A']
    types: [completed]

jobs:
  print-current-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print current branch
        uses: echo ${{ github.ref }}
